### ISSUE TITLE
Doesn't work when you choose different stats.

### ISSUE THREAD

**Issue by bryanjenningz** [FrankBowers24/d3-bayarea#1]
If you try to view different stats, the chart turns into plain text and the map doesn't adjust.
If you open the console, you'll see the error.
Error: Cannot set property index of undefined.
![screen shot 2015-10-09 at 1 10 22 pm](https://cloud.githubusercontent.com/assets/7637655/10404383/31e24b46-6e87-11e5-937e-cbb3342b810c.png)

**Comment by FrankBowers24** [comment]
The dataset property of HTMLElement is no longer supported by latest version of Chrome.  I removed the dependence on dataset.  This issue is Fixed
